defaults:
  - _self_
hydra:
  job:
    chdir: True
    name: "${general.name}"
  run:
    dir: "${general.experiment_path}"
general:
  name: ""
  root: "/mnt/localdisk/gabriel/nodocker/nuclear"
  experiment_path: "${general.root}/${general.name}"
  device: "cuda:0"
  distributed: False
  seed: 13
  img_size: 40
train:
  dataset: "CELEBA"
  max_epochs: 400
  max_steps: 100000
  batch_size: 512
  pin_memory: True
  num_workers: 4
  persistent_workers: True
  optimizer:
    lr: 1e-4
    momentum: 0.98
  scheduler:
    gamma: 0.5
    step_size: 200
  loss_coefs:
    alpha: 0.99
    beta: 0.05
val:
  dataset: "CELEBA"
  batch_size: 512
  pin_memory: True
  num_workers: 4
  persistent_workers: True
model:
  dim: 25